import 'package:abs_api/abs_api.dart';

final fakeBookSession = PlaybackSession(
  id: 'test-session',
  libraryItemId: 'item-1',
  userId: 'user-id',
  libraryId: 'library-id',
  mediaType: .book,
  mediaMetadata: const .book(),
  chapters: [],
  duration: const Duration(hours: 1),
  playMethod: .directPlay,
  mediaPlayer: 'test',
  date: '2026-06-13',
  dayOfWeek: 'Saturday',
  timeListening: .zero,
  startTime: .zero,
  currentTime: .zero,
  startedAt: .now(),
  updatedAt: .now(),
);

final fakeLocalBookSession = PlaybackSession(
  id: 'local-test-session',
  libraryItemId: 'item-1',
  userId: 'user-id',
  libraryId: 'library-id',
  mediaType: .book,
  mediaMetadata: const .book(),
  chapters: [],
  duration: const Duration(hours: 1),
  playMethod: .local,
  mediaPlayer: 'test',
  date: '2026-06-13',
  dayOfWeek: 'Saturday',
  timeListening: .zero,
  startTime: .zero,
  currentTime: .zero,
  startedAt: .now(),
  updatedAt: .now(),
);
