include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_single_quotes: true
    always_use_package_imports: true
    require_trailing_commas: true
    directives_ordering: true
    unnecessary_lambdas: true
    sort_pub_dependencies: true

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
