// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:storii/storage/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AudioMetaTagsAdapter());
    registerAdapter(AudioTrackAdapter());
    registerAdapter(AuthorAdapter());
    registerAdapter(BookChapterAdapter());
    registerAdapter(BookMediaAdapter());
    registerAdapter(BookMetadataAdapter());
    registerAdapter(FileMetadataAdapter());
    registerAdapter(LibraryItemAdapter());
    registerAdapter(MediaProgressAdapter());
    registerAdapter(PodcastEpisodeAdapter());
    registerAdapter(PodcastEpisodeEnclosureAdapter());
    registerAdapter(PodcastMediaAdapter());
    registerAdapter(PodcastMetadataAdapter());
    registerAdapter(SeriesAdapter());
    registerAdapter(SeriesProgressAdapter());
    registerAdapter(ServerAdapter());
    registerAdapter(UserDomainAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AudioMetaTagsAdapter());
    registerAdapter(AudioTrackAdapter());
    registerAdapter(AuthorAdapter());
    registerAdapter(BookChapterAdapter());
    registerAdapter(BookMediaAdapter());
    registerAdapter(BookMetadataAdapter());
    registerAdapter(FileMetadataAdapter());
    registerAdapter(LibraryItemAdapter());
    registerAdapter(MediaProgressAdapter());
    registerAdapter(PodcastEpisodeAdapter());
    registerAdapter(PodcastEpisodeEnclosureAdapter());
    registerAdapter(PodcastMediaAdapter());
    registerAdapter(PodcastMetadataAdapter());
    registerAdapter(SeriesAdapter());
    registerAdapter(SeriesProgressAdapter());
    registerAdapter(ServerAdapter());
    registerAdapter(UserDomainAdapter());
  }
}
